name: 'PoC GitHub Action test'
description: 'An initial test GitHub action for simple proof of concept'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  time: # id of output
    description: 'An initial test GitHub action for simple proof of concept- output description'
runs:
  using: 'node12'
  main: 'index.js'